-- 用户Champion订阅支付记录表
-- 记录每次支付的详细信息，与payment_record表关联
CREATE TABLE IF NOT EXISTS `user_champion_subscription_record` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `user_id` int(11) NOT NULL COMMENT '用户ID',
  `novel_id` int(11) NOT NULL COMMENT '小说ID',
  `payment_record_id` int(11) NOT NULL COMMENT '关联的payment_record表ID',
  `tier_level` int(2) NOT NULL COMMENT '订阅等级 (1: Martial Cultivator, 2: Profound Realm, 3: Martial Lord)',
  `tier_name` varchar(50) NOT NULL COMMENT '订阅等级名称',
  `monthly_price` decimal(10,2) NOT NULL COMMENT '月费价格',
  `payment_amount` decimal(10,2) NOT NULL COMMENT '实际支付金额',
  `payment_method` varchar(20) NOT NULL COMMENT '支付方式 (stripe, paypal)',
  `payment_status` varchar(20) NOT NULL DEFAULT 'pending' COMMENT '支付状态 (pending, completed, failed, refunded)',
  `subscription_type` varchar(20) NOT NULL DEFAULT 'new' COMMENT '订阅类型 (new: 新订阅, renew: 续费, upgrade: 升级, extend: 延长)',
  `subscription_duration_months` int(3) NOT NULL DEFAULT 1 COMMENT '订阅时长(月)',
  `start_date` datetime NOT NULL COMMENT '订阅开始时间',
  `end_date` datetime NOT NULL COMMENT '订阅结束时间',
  `is_active` tinyint(1) NOT NULL DEFAULT 1 COMMENT '是否激活',
  `auto_renew` tinyint(1) NOT NULL DEFAULT 0 COMMENT '是否自动续费',
  `transaction_id` varchar(255) DEFAULT NULL COMMENT '第三方交易ID (Stripe PaymentIntent ID, PayPal Order ID等)',
  `stripe_payment_intent_id` varchar(255) DEFAULT NULL COMMENT 'Stripe PaymentIntent ID',
  `paypal_order_id` varchar(255) DEFAULT NULL COMMENT 'PayPal Order ID',
  `stripe_customer_id` varchar(255) DEFAULT NULL COMMENT 'Stripe Customer ID',
  `paypal_payer_id` varchar(255) DEFAULT NULL COMMENT 'PayPal Payer ID',
  `card_brand` varchar(50) DEFAULT NULL COMMENT '卡品牌 (visa, mastercard, amex等)',
  `card_last4` varchar(4) DEFAULT NULL COMMENT '卡号后四位',
  `card_exp_month` int(2) DEFAULT NULL COMMENT '过期月份',
  `card_exp_year` int(4) DEFAULT NULL COMMENT '过期年份',
  `currency` varchar(3) NOT NULL DEFAULT 'USD' COMMENT '货币类型',
  `exchange_rate` decimal(10,6) DEFAULT NULL COMMENT '汇率',
  `local_amount` decimal(10,2) DEFAULT NULL COMMENT '本地货币金额',
  `local_currency` varchar(3) DEFAULT NULL COMMENT '本地货币',
  `discount_amount` decimal(10,2) DEFAULT 0.00 COMMENT '折扣金额',
  `discount_code` varchar(50) DEFAULT NULL COMMENT '折扣码',
  `tax_amount` decimal(10,2) DEFAULT 0.00 COMMENT '税费',
  `fee_amount` decimal(10,2) DEFAULT 0.00 COMMENT '手续费',
  `refund_amount` decimal(10,2) DEFAULT 0.00 COMMENT '退款金额',
  `refund_reason` varchar(255) DEFAULT NULL COMMENT '退款原因',
  `refund_date` datetime DEFAULT NULL COMMENT '退款时间',
  `notes` text DEFAULT NULL COMMENT '备注信息',
  `ip_address` varchar(45) DEFAULT NULL COMMENT '支付IP地址',
  `user_agent` text DEFAULT NULL COMMENT '用户代理',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  KEY `idx_user_id` (`user_id`),
  KEY `idx_novel_id` (`novel_id`),
  KEY `idx_payment_record_id` (`payment_record_id`),
  KEY `idx_transaction_id` (`transaction_id`),
  KEY `idx_stripe_payment_intent_id` (`stripe_payment_intent_id`),
  KEY `idx_paypal_order_id` (`paypal_order_id`),
  KEY `idx_payment_status` (`payment_status`),
  KEY `idx_subscription_type` (`subscription_type`),
  KEY `idx_created_at` (`created_at`),
  KEY `idx_start_date` (`start_date`),
  KEY `idx_end_date` (`end_date`),
  CONSTRAINT `fk_user_champion_subscription_record_user_id` FOREIGN KEY (`user_id`) REFERENCES `user` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_user_champion_subscription_record_novel_id` FOREIGN KEY (`novel_id`) REFERENCES `novel` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_user_champion_subscription_record_payment_record_id` FOREIGN KEY (`payment_record_id`) REFERENCES `payment_record` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='用户Champion订阅支付记录表';
